package com.example.smedcan.data.model;
// Generated Aug 24, 2021 9:50:53 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


    private Integer did;
    private String dname;
    private String gender;
    private String nic;
    private String address;
    private int coNumber;
    private String email;
    private String otperiod;
    private String edQualification;
    private String aqualification;
    private String username;
    private String password;
    private String confirmPassword;
    private String dtype;
    private Double price;
    private String imgurl;

    public Doctor() {
    }


    public Doctor(String dname, String gender, String nic, String address, int coNumber, String email, String otperiod, String edQualification, String aqualification, String username, String password, String confirmPassword) {
        this.dname = dname;
        this.gender = gender;
        this.nic = nic;
        this.address = address;
        this.coNumber = coNumber;
        this.email = email;
        this.otperiod = otperiod;
        this.edQualification = edQualification;
        this.aqualification = aqualification;
        this.username = username;
        this.password = password;
        this.confirmPassword = confirmPassword;
    }
    public Doctor(String dname, String gender, String nic, String address, int coNumber, String email, String otperiod, String edQualification, String aqualification, String username, String password, String confirmPassword, String dtype, Double price, String imgurl) {
        this.dname = dname;
        this.gender = gender;
        this.nic = nic;
        this.address = address;
        this.coNumber = coNumber;
        this.email = email;
        this.otperiod = otperiod;
        this.edQualification = edQualification;
        this.aqualification = aqualification;
        this.username = username;
        this.password = password;
        this.confirmPassword = confirmPassword;
        this.dtype = dtype;
        this.price = price;
        this.imgurl = imgurl;
    }

    public Integer getDid() {
        return this.did;
    }

    public void setDid(Integer did) {
        this.did = did;
    }
    public String getDname() {
        return this.dname;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNic() {
        return this.nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    public int getCoNumber() {
        return this.coNumber;
    }

    public void setCoNumber(int coNumber) {
        this.coNumber = coNumber;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getOtperiod() {
        return this.otperiod;
    }

    public void setOtperiod(String otperiod) {
        this.otperiod = otperiod;
    }
    public String getEdQualification() {
        return this.edQualification;
    }

    public void setEdQualification(String edQualification) {
        this.edQualification = edQualification;
    }
    public String getAqualification() {
        return this.aqualification;
    }

    public void setAqualification(String aqualification) {
        this.aqualification = aqualification;
    }
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    public String getConfirmPassword() {
        return this.confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }
    public String getDtype() {
        return this.dtype;
    }

    public void setDtype(String dtype) {
        this.dtype = dtype;
    }
    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }
    public String getImgurl() {
        return this.imgurl;
    }

    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }
}





